micronaut:
  application:
    name: micronautguide

datasources:
  default:
    dialect: ANSI
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: password

flyway:
  datasources:
    default:
      enabled: true
